export const SWITCH_MAIN_TAB = 'SWITCH_MAIN_TAB';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDDEN_MODAL = 'HIDDEN_MODAL';
export const SHOW_TOAST = 'SHOW_TOAST';
export const HIDDEN_TOAST = 'HIDDEN_TOAST';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDDEN_LOADING = 'HIDDEN_LOADING';

/****************搜索连接相关****************/
//HOME ACTION TYPES
export const START_SEARCH_DEVICE = 'START_SEARCH_DEVICE';
export const STOP_SEARCH_DEVICE = 'STOP_SEARCH_DEVICE';
export const UPDATE_DEVICE_LIST = 'UPDATE_DEVICE_LIST';
export const START_DEVICE_CONNECT = 'START_DEVICE_CONNECT';
export const SUCCESS_DEVICE_CONNECT = 'SUCCESS_DEVICE_CONNECT';
export const FAIL_DEVICE_CONNECT = 'FAIL_DEVICE_CONNECT';

//DEVICE ACTION TYPE
export const DEVICE_DISCONNECT = 'DEVICE_DISCONNECT';
export const SUCCESS_DEVICE_DISCONNECT = 'SUCCESS_DEVICE_DISCONNECT';
export const FAIL_DEVICE_DISCONNECT = 'FAIL_DEVICE_DISCONNECT';

export const CLEAR_DEVICE_DATA = 'CLEAR_DEVICE_DATA';

export const ERROR = 'ERROR';

/****************读取电压****************/
export const START_READ_VOLTAGE = 'START_READ_VOLTAGE';
export const READ_VOLTAGE = 'READ_VOLTAGE';
export const READ_VERSION = 'READ_VERSION';
export const READ_SLEEPDATA = 'READ_SLEEPDATA';
export const READ_MACADDRESS = 'READ_MACADDRESS';
export const READ_SLEEPSTATUS = 'READ_SLEEPSTATUS';
export const READ_LOG = 'READ_LOG';
export const CLEAR_LOG = 'CLEAR_LOG';

/****************充放气测试****************/
//进入手控模式
export const START_MANUAL = 'START_MANUAL';
export const SUCCESS_START_MANUAL = 'SUCCESS_START_MANUAL';

//退出手控模式
export const STOP_MANUAL = 'STOP_MANUAL';
export const SUCCESS_STOP_MANUAL = 'SUCCESS_STOP_MANUAL';